### ISSUE TITLE
About the PSNR

### ISSUE THREAD

**Issue by SungJin-Lee** [csbhr/Deep-Blind-VSR#2]
![avg_psnr](https://user-images.githubusercontent.com/48192083/145962587-f293b828-c6dc-4c28-9fcb-bc51f7d8bc75.jpg)
I have a question about test

In the paper DBVSR in ICCV,(
 https://openaccess.thecvf.com/content/ICCV2021/papers/Pan_Deep_Blind_Video_Super-Resolution_ICCV_2021_paper.pdf) 
The PSNR in the benchmark datasets((REDS) dataset) with unknown Gaussian kernels is 29.18
However, when I tested it on unknown Gaussian kernel, average PSNR was 29.087...
is there any problem with my programming environment??
I am using torch 1.7.1 and python 3.8.12

**Comment by csbhr** [comment]
We have tested that the results reported in the Paper can be reproduced on the environment with PyTorch 0.4.1 and PyTorch 1.2.0.

You can build a new environment following https://github.com/csbhr/Deep-Blind-VSR#dependencies, and test with the commands in https://github.com/csbhr/Deep-Blind-VSR#quick-test

**Comment by SungJin-Lee** [comment]
I've get it!!! Thank you for answering!!!
