### ISSUE TITLE
requires at least pytorch version 1.3.0

### ISSUE THREAD

**Issue by SungJin-Lee** [csbhr/Deep-Blind-VSR#3]
<img width="703" alt="image" src="https://user-images.githubusercontent.com/48192083/146333263-cecb4d54-2676-4418-881c-c93ecb6f61b4.png">

I updated PyTorch version to 0.4.1 as your experiment setting and tried to run pytorch-pwc code for checking
https://github.com/sniklaus/pytorch-pwc
However, it said pytorch-pwc need PyTorch version later than 1.3.0.
If then, the fore mentioned  in my issue, the PSNR and SSIM measure would be the same in my previous issue.....
How did you build https://github.com/sniklaus/pytorch-pwc with pytorch version 0.4.1.???????
I need help

**Comment by csbhr** [comment]
We use the "pytorch-pwc" code downloaded two year ago from https://github.com/sniklaus/pytorch-pwc.

And the "pytorch-pwc" code (https://github.com/sniklaus/pytorch-pwc) have been updated few months ago, which requires new PyTorch version.

We plan to upgrade our codes to support the new version of PyTorch in the near future.

**Comment by SungJin-Lee** [comment]
Thank you for your valuable and rapid comment...
However, I should check the PSNR and SSIM of this code because of my individual project...
May I know another programming environment to get the PSNR and SSIM in the paper, please? I'm sorry, but I'm afraid that I cannot do my project before I get the same PSNR in the ICCV paper with this code.
Thank you

**Comment by SungJin-Lee** [comment]
I mean such as later pytorch version than 1.3.0.

**Comment by csbhr** [comment]
Sorry, I have been occupied with other things recently, and I don't have time to adapt the code for the time being. You can adapt the code to the higher version of PyTorch for your project, or you can try lower PyTorch version like 1.2.0.

**Comment by SungJin-Lee** [comment]
That's okay... I am very thankful that you replied to this comment.
