### ISSUE TITLE
论文版本

### ISSUE THREAD

**Issue by zdyshine** [csbhr/Deep-Blind-VSR#5]
感谢您开源这么好的工作，我之前在网络有看到另外一篇潘老师的Deep Blind Video Super-resolution文章，blog连接如下:https://blog.csdn.net/qq_33590958/article/details/110195062。有请问这两个文章什么联系吗？

**Comment by csbhr** [comment]
你好，感谢关注。arXiv上的那一篇存在一些不足，论文没有中。而本Github库的这篇论文是对算法和实验进行了重新设计，发表在了ICCV2021上。
